// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCTollFwrtQChqWRCzOF3CTQFUGDcv-skc',
    appId: '1:911532524791:web:2024fc3058f3942f187ff2',
    messagingSenderId: '911532524791',
    projectId: 'finan-4854e',
    authDomain: 'finan-4854e.firebaseapp.com',
    databaseURL: 'https://finan-4854e-default-rtdb.firebaseio.com',
    storageBucket: 'finan-4854e.firebasestorage.app',
    measurementId: 'G-X0Q6TFQTF8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDvNFNTp2AhuTfSodOUEedt5yjuhPqDuzY',
    appId: '1:911532524791:android:d047730cae9f4000187ff2',
    messagingSenderId: '911532524791',
    projectId: 'finan-4854e',
    databaseURL: 'https://finan-4854e-default-rtdb.firebaseio.com',
    storageBucket: 'finan-4854e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBrgP-mNKSHOXUGW6aCaaae9TOcLOUcbPM',
    appId: '1:911532524791:ios:7343f02338cca810187ff2',
    messagingSenderId: '911532524791',
    projectId: 'finan-4854e',
    databaseURL: 'https://finan-4854e-default-rtdb.firebaseio.com',
    storageBucket: 'finan-4854e.firebasestorage.app',
    iosClientId: '911532524791-75b0joj6gtgpcvuriisckd1at01aerh3.apps.googleusercontent.com',
    iosBundleId: 'com.example.finan',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBrgP-mNKSHOXUGW6aCaaae9TOcLOUcbPM',
    appId: '1:911532524791:ios:7343f02338cca810187ff2',
    messagingSenderId: '911532524791',
    projectId: 'finan-4854e',
    databaseURL: 'https://finan-4854e-default-rtdb.firebaseio.com',
    storageBucket: 'finan-4854e.firebasestorage.app',
    iosClientId: '911532524791-75b0joj6gtgpcvuriisckd1at01aerh3.apps.googleusercontent.com',
    iosBundleId: 'com.example.finan',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCTollFwrtQChqWRCzOF3CTQFUGDcv-skc',
    appId: '1:911532524791:web:8c9530465db84a9e187ff2',
    messagingSenderId: '911532524791',
    projectId: 'finan-4854e',
    authDomain: 'finan-4854e.firebaseapp.com',
    databaseURL: 'https://finan-4854e-default-rtdb.firebaseio.com',
    storageBucket: 'finan-4854e.firebasestorage.app',
    measurementId: 'G-98QF2CPMTF',
  );
}
